Name:           perl-XAS
Version:        0.06
Release:        1%{?dist}
Summary:        XAS Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/XAS/
Source0:        http://www.cpan.org/modules/by-module/XAS/XAS-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Badger) >= 0.09
BuildRequires:  perl(Config::IniFiles) >= 2.72
BuildRequires:  perl(DateTime) >= 0.53
BuildRequires:  perl(DateTime::Format::Pg)
BuildRequires:  perl(DateTime::Format::Strptime) >= 1.1
BuildRequires:  perl(File::Pid)
BuildRequires:  perl(Hash::Merge) >= 0.12
BuildRequires:  perl(JSON::XS) >= 2.27
BuildRequires:  perl(LockFile::Simple) >= 0.207
BuildRequires:  perl(Log::Log4perl)
BuildRequires:  perl(MIME::Lite) >= 3.027
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Params::Validate) >= 0.92
BuildRequires:  perl(POE) >= 1.35
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Try::Tiny::Retry) >= 0.0
Requires:       perl(Badger) >= 0.09
Requires:       perl(Config::IniFiles) >= 2.72
Requires:       perl(DateTime) >= 0.53
Requires:       perl(DateTime::Format::Pg)
Requires:       perl(DateTime::Format::Strptime) >= 1.1
Requires:       perl(File::Pid)
Requires:       perl(Hash::Merge) >= 0.12
Requires:       perl(JSON::XS) >= 2.27
Requires:       perl(LockFile::Simple) >= 0.207
Requires:       perl(Log::Log4perl)
Requires:       perl(MIME::Lite) >= 3.027
Requires:       perl(Params::Validate) >= 0.92
Requires:       perl(POE) >= 1.35
Requires:       perl(Try::Tiny::Retry) >= 0.0
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

# filter out Win32 stuff.

%{?filter_setup: %{?perl_default_filter} }
%filter_from_requires /Win32/d
%filter_setup

%description
This is middleware for Perl. It is cross platform capable.

%prep
%setup -q -n XAS-%{version}

%build
%{__perl} Build.PL installdirs=site
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes perl-XAS.spec README
%{perl_sitelib}/*
/usr/local/share/man/man3/*

%changelog
* Tue Sep 24 2013 kesteb 0.07-1
- Specfile autogenerated by cpanspec 1.78.
